version = "1"

[ingredients]
hello_g = "Hello Global Var"
bye_g = "Bye Global Var"

[sigil.global]
description = "Prints global vars"
language = "shell"
run = '''
echo {{hello_g}} 
echo {{bye_g}}
'''

[sigil.hello]
description = "A Simple Welcome spell"
language = "shell"
run = "echo 'Welcome to Grimoire!'"

# Testing default language fallback
[sigil.bye]
description = "Bye Spell"
run = "echo 'Bye From Grimoire'"

# Testing Options
[sigil.options]
description = "Try out option selection"
run = "echo 'Selection option is {{opt}}'"

[sigil.options.args.opt]
type = "select"
choices = [
  "Option 1",
  "Option 2",
  "Option 3"
]
default = "Option 1"

# Languages
[sigil.hello_py]
language = "python"
description = "Hello in Python"
run = "print('Hello World')"

[sigil.hello_js]
language = "javascript"
description = "Hello in javascript"
run = """
console.log("Hello World");
"""

[sigil.hello_c]
language = "c"
description = "Hello in C"
run = '''
#include <stdio.h>

int main() {
  printf("Hello World\n");
  return 0;
}
'''


# Project related sigils (For testing purposes only)
[sigil.build]
language = "shell"
description = "Build the project (Use --release to build in release mode)"
run = "cargo build --bin grim"

[sigil.clean]
language = "shell"
description = "Clean up build artifacts"
run = "cargo clean"
