# This Grimoire.toml is an example

version = "1"

[ingredients]
hello_g = "Hello Global Var"
bye_g = "Bye Global Var"
greeting = "This is a global greeting"

[sigil.global]
description = "Prints global vars"
language = "shell"
run = '''
echo {{hello_g}} 
echo {{bye_g}}
'''

[sigil.silent_ex]
silent = true
description = "Run in silent mode. Prints only the output"
language = "c++"
run = '''
#include <iostream>

int main() {
  std::cout << "Hello World" << std::endl;
  return 0;
}
'''

[sigil.hello]
description = "A Simple Welcome spell"
language = "shell"
run = "echo 'Welcome to Grimoire!'"

# Testing default language fallback
[sigil.bye]
description = "Bye Spell"
run = "echo 'Bye From Grimoire'"

# Testing Options
[sigil.options]
description = "Try out option selection"
run = "echo 'Selection option is {{opt}}'"

[sigil.options.args.opt]
type = "select"
choices = [
  "Option 1",
  "Option 2",
  "Option 3"
]
default = "Option 1"

# Languages
[sigil.hello_py]
language = "python"
description = "Hello in Python"
run = "print('Hello World')"

[sigil.hello_js]
language = "javascript"
description = "Hello in javascript"
run = """
console.log("Hello World");
"""

[sigil.hello_c]
language = "c"
description = "Hello in C"
run = '''
#include <stdio.h>

int main() {
  printf("Hello World\n");
  return 0;
}
'''


# Project related sigils (For testing purposes only)
[sigil.build]
language = "shell"
description = "Build the project (Use --release to build in release mode)"
run = "cargo build --bin grim"

[sigil.clean]
language = "shell"
description = "Clean up build artifacts"
run = "cargo clean"

# Run script file
## Python
[sigil.py]
description = "Cast the python script interactively"
silent = true
run = "scripts/test_grim.py {{target}}"

[sigil.py.args.target]
type = "select"
choices = [
  "Frieren",
  "Fern",
  "Stark",
  "Hero of the South"
]
default = "Frieren"

## Rust
[sigil.rs]
description = "Run a Rust file"
silent = true
run = "scripts/test_grim.rs"

## Bash
[sigil.sh]
description = "Run a shell script file"
silent = true
run = "scripts/test_grim.sh '{{greeting}}'"

## Node
[sigil.js]
description = "Cast the Node script"
silent = true
run = "scripts/test_grim.js '{{target}}'"

[sigil.js.args.target]
type = "select"
choices = [
  "Frieren",
  "Fern",
  "Stark",
  "Hero of the South"
]
default = "Frieren"

# Interactive Arguments with CLI flags
[sigil.intargflag]
description = "Showing working of CLI flags with Interactive arguments"
run = "cargo run --bin grim --release -- {{flags}}"

[sigil.intargflag.args.flags]
type = "select"
choices = [
  "sigils",
  "cast py",
  "cast js",
  "cast rs",
  "cast sh",
  "--help",
  "--version"
]
default = "sigils"
